package com.student.techladies.mapper;


import com.student.techladies.common.NoticeResponse;
import com.student.techladies.model.Collection;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated
     */
    int insert(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated
     */
    int insertSelective(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated
     */
    Collection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Collection record);

    int selectCountByUserId(@Param("userId") int parseInt);

    List<NoticeResponse> selectInfoByUserId(@Param("userId") int parseInt);

    void deleteByPId(@Param("userId") int parseInt,@Param("post") int id);

    int selectCountByUserIdAndId(@Param("userId") int parseInt,@Param("post")  int id);

    int selectNum(@Param("userId") int parseInt, @Param("postId") int postId);
}