package com.student.techladies.mapper;


import com.student.techladies.model.Fans;
import org.apache.ibatis.annotations.Param;

public interface FansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans
     *
     * @mbggenerated
     */
    int insert(Fans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans
     *
     * @mbggenerated
     */
    int insertSelective(Fans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans
     *
     * @mbggenerated
     */
    Fans selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Fans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Fans record);

    int selectCount(@Param("userId") int id);
}