package com.student.techladies.mapper;


import com.student.techladies.common.NoticeResponse;
import com.student.techladies.model.Foucus;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FoucusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foucus
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foucus
     *
     * @mbggenerated
     */
    int insert(Foucus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foucus
     *
     * @mbggenerated
     */
    int insertSelective(Foucus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foucus
     *
     * @mbggenerated
     */
    Foucus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foucus
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Foucus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foucus
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Foucus record);

    int selectCount(@Param("userId") int id);

    int selectCountByUserId(@Param("userId") String userId);

    List<NoticeResponse> selectInfoByUserId(@Param("userId") int parseInt);

    int selectCountByIdd(@Param("userId") int userId,@Param("id")  int id);

    void deleteByd(@Param("userId") int userId,@Param("id") int id);

    int selectfocusCount(@Param("userId") int id);

    int selectfansCount(@Param("userId")int id);
}