package com.student.techladies.mapper;


import com.student.techladies.common.NoticeResponse;
import com.student.techladies.model.Like;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbggenerated
     */
    int insert(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbggenerated
     */
    int insertSelective(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbggenerated
     */
    Like selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Like record);

    int selectCount(@Param("userId") Integer userId,@Param("id") int id);

    void deleteByPId(@Param("userId") int id, @Param("id") int parseInt);

    int selectCountByUserId(@Param("userId") Integer userId);

    List<NoticeResponse> selectInfoByUserId(@Param("userId") int parseInt);

    int selectNum(@Param("userId") int parseInt,@Param("postId") int postId);
}