package com.student.techladies.mapper;


import com.student.techladies.common.NoticeResponse;
import com.student.techladies.model.Notice;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface NoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    int insert(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    int insertSelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    Notice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Notice record);

    List<Notice> selectListById(int parseInt);

    void delete(@Param("type") String like,@Param("content")  String s,@Param("userId") int parseInt);

    List<NoticeResponse> selectlikeInfoByUserId(@Param("userId") int parseInt,@Param("type") String like);

    List<NoticeResponse> selectfoucusInfoByUserId(@Param("userId") int parseInt,@Param("type") String like);

    List<NoticeResponse> selectcommentInfoByUserId(@Param("userId") int parseInt,@Param("type") String like);

    List<NoticeResponse> selectcollectionInfoByUserId(@Param("userId") int parseInt,@Param("type") String like);

    void deleteby(@Param("userId") int userId,@Param("type") String type);

    void deleteByPostId(@Param("userId") int parseInt,@Param("type") String type);

    int selectCountByUserId(@Param("userId") int parseInt,@Param("type") String type);

    int selectCount(@Param("userId") int parseInt,@Param("type") String type);
}