package com.student.techladies.mapper;


import com.student.techladies.model.Post;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    int insert(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    int insertSelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    Post selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Post record);

    List<Post> selectBycondition(@Param("content") String content,@Param("type") String type, @Param("tag") List<String> s);

    void updateLikeNum(@Param("id") int id,@Param("type") String type);

    List<Post> postAndCollection(@Param("type") String type,@Param("userId")Integer userId);

    void updateCollectionNum(@Param("id") int id,@Param("type") String add);

    List<Post> selectPostListBy(@Param("userId") int id);

    List<Post> selectCollectionListBy(@Param("userId") int id);

    void addCommentNum(@Param("postId") Integer postId);
}