package com.student.techladies.model;

import java.util.Date;

public class Fans {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.fans_id
     *
     * @mbggenerated
     */
    private Integer fansId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.id
     *
     * @return the value of fans.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.id
     *
     * @param id the value for fans.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.fans_id
     *
     * @return the value of fans.fans_id
     *
     * @mbggenerated
     */
    public Integer getFansId() {
        return fansId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.fans_id
     *
     * @param fansId the value for fans.fans_id
     *
     * @mbggenerated
     */
    public void setFansId(Integer fansId) {
        this.fansId = fansId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.user_id
     *
     * @return the value of fans.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.user_id
     *
     * @param userId the value for fans.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.type
     *
     * @return the value of fans.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.type
     *
     * @param type the value for fans.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.create_time
     *
     * @return the value of fans.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.create_time
     *
     * @param createTime the value for fans.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}