package com.student.techladies.model;

import java.util.Date;

public class Foucus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foucus.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foucus.focus_id
     *
     * @mbggenerated
     */
    private Integer focusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foucus.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foucus.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foucus.id
     *
     * @return the value of foucus.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foucus.id
     *
     * @param id the value for foucus.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foucus.focus_id
     *
     * @return the value of foucus.focus_id
     *
     * @mbggenerated
     */
    public Integer getFocusId() {
        return focusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foucus.focus_id
     *
     * @param focusId the value for foucus.focus_id
     *
     * @mbggenerated
     */
    public void setFocusId(Integer focusId) {
        this.focusId = focusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foucus.user_id
     *
     * @return the value of foucus.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foucus.user_id
     *
     * @param userId the value for foucus.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foucus.create_time
     *
     * @return the value of foucus.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foucus.create_time
     *
     * @param createTime the value for foucus.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}