package com.student.techladies.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Post {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.tag
     *
     * @mbggenerated
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.likes
     *
     * @mbggenerated
     */
    private Integer likes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.comments
     *
     * @mbggenerated
     */
    private Integer comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.focus
     *
     * @mbggenerated
     */
    private Integer focus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.forwards
     *
     * @mbggenerated
     */
    private Integer forwards;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.create_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

    private String imgUrl ;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.id
     *
     * @return the value of post.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.id
     *
     * @param id the value for post.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.user_id
     *
     * @return the value of post.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.user_id
     *
     * @param userId the value for post.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.content
     *
     * @return the value of post.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.content
     *
     * @param content the value for post.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.type
     *
     * @return the value of post.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.type
     *
     * @param type the value for post.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.tag
     *
     * @return the value of post.tag
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.tag
     *
     * @param tag the value for post.tag
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.likes
     *
     * @return the value of post.likes
     *
     * @mbggenerated
     */
    public Integer getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.likes
     *
     * @param likes the value for post.likes
     *
     * @mbggenerated
     */
    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.comments
     *
     * @return the value of post.comments
     *
     * @mbggenerated
     */
    public Integer getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.comments
     *
     * @param comments the value for post.comments
     *
     * @mbggenerated
     */
    public void setComments(Integer comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.focus
     *
     * @return the value of post.focus
     *
     * @mbggenerated
     */
    public Integer getFocus() {
        return focus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.focus
     *
     * @param focus the value for post.focus
     *
     * @mbggenerated
     */
    public void setFocus(Integer focus) {
        this.focus = focus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.forwards
     *
     * @return the value of post.forwards
     *
     * @mbggenerated
     */
    public Integer getForwards() {
        return forwards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.forwards
     *
     * @param forwards the value for post.forwards
     *
     * @mbggenerated
     */
    public void setForwards(Integer forwards) {
        this.forwards = forwards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.create_time
     *
     * @return the value of post.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.create_time
     *
     * @param createTime the value for post.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }
}