package com.student.techladies.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column df_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column df_user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column df_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column df_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column df_user.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column df_user.img_url
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column df_user.post_num
     *
     * @mbggenerated
     */
    private Integer postNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column df_user.fans_num
     *
     * @mbggenerated
     */
    private Integer fansNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column df_user.flower_num
     *
     * @mbggenerated
     */
    private Integer flowerNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column df_user.create_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column df_user.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column df_user.id
     *
     * @return the value of df_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column df_user.id
     *
     * @param id the value for df_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column df_user.name
     *
     * @return the value of df_user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column df_user.name
     *
     * @param name the value for df_user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column df_user.email
     *
     * @return the value of df_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column df_user.email
     *
     * @param email the value for df_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column df_user.password
     *
     * @return the value of df_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column df_user.password
     *
     * @param password the value for df_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column df_user.status
     *
     * @return the value of df_user.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column df_user.status
     *
     * @param status the value for df_user.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column df_user.img_url
     *
     * @return the value of df_user.img_url
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column df_user.img_url
     *
     * @param imgUrl the value for df_user.img_url
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column df_user.post_num
     *
     * @return the value of df_user.post_num
     *
     * @mbggenerated
     */
    public Integer getPostNum() {
        return postNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column df_user.post_num
     *
     * @param postNum the value for df_user.post_num
     *
     * @mbggenerated
     */
    public void setPostNum(Integer postNum) {
        this.postNum = postNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column df_user.fans_num
     *
     * @return the value of df_user.fans_num
     *
     * @mbggenerated
     */
    public Integer getFansNum() {
        return fansNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column df_user.fans_num
     *
     * @param fansNum the value for df_user.fans_num
     *
     * @mbggenerated
     */
    public void setFansNum(Integer fansNum) {
        this.fansNum = fansNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column df_user.flower_num
     *
     * @return the value of df_user.flower_num
     *
     * @mbggenerated
     */
    public Integer getFlowerNum() {
        return flowerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column df_user.flower_num
     *
     * @param flowerNum the value for df_user.flower_num
     *
     * @mbggenerated
     */
    public void setFlowerNum(Integer flowerNum) {
        this.flowerNum = flowerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column df_user.create_time
     *
     * @return the value of df_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column df_user.create_time
     *
     * @param createTime the value for df_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column df_user.remark
     *
     * @return the value of df_user.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column df_user.remark
     *
     * @param remark the value for df_user.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}